### ISSUE TITLE
Lisa Workshop Cannot Link Pascal with "IF" Statements

### ISSUE THREAD

**Issue by krfkeith** [rayarachelian/lisaem-1.2.x#2]
There is apparently a bug in the emulator which precludes linking Pascal code which contains IF statements. Obviously, this makes the compiler effectively useless.

**Comment by rayarachelian** [comment]
This seems to be a CPU related bug, might be able to fix this once 1.3 is ready.  (Other issues are the Desktop menu repeating and the scroll bar thumbs and arrows being wrong.)

**Comment by krfkeith** [comment]
That's good to hear! Any possible ETA on 1.3? 😉

**Comment by rayarachelian** [comment]
I'd like to, but there's blocking bugs that I haven't been able to find.  One thing I've been planning on doing is to run both 1.3's CPU core and 1.2.6 simultaneously and compare the runs opcode for opcode to see where it's breaking, but that will take some time (on the order of weeks/months.)
