### ISSUE TITLE
Build script not working on Ubuntu

### ISSUE THREAD

**Issue by gnud** [rayarachelian/lisaem-1.2.x#7]
A small bug which is not documented in the installation process.

```
:~/source/lisaem-1.2.x$ for i in bin resources lisa wxui generator cpu68k; do if [ ! -d ./$i ]; then echo $i; fi; done
bin # <-- meaning it likes to have the bin directory created
```
when I list the files from the clone GIT repo, the bin directory is missing, can you update Readme to mention this or update the build script to echo the missing directories :), thanks.

**Comment by rayarachelian** [comment]
Thanks guys
